# Generated by Django 3.0.8 on 2026-01-21 20:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20200722_0405'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sortno',
            new_name='quantity',
        ),
        migrations.AddField(
            model_name='product',
            name='show_size',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='unit_of_measurement',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
