# Generated by Django 3.0.8 on 2026-01-26 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20260121_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='cpf',
            field=models.CharField(default='', max_length=14, unique=True),
        ),
        migrations.AddField(
            model_name='buyer',
            name='escolaridade',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='buyer',
            name='estado_civil',
            field=models.CharField(choices=[('solteiro', 'Solteiro(a)'), ('casado', 'Casado(a)'), ('divorciado', 'Divorciado(a)'), ('viuvo', 'Viúvo(a)'), ('separado', 'Separado(a)'), ('uniao_estavel', 'União Estável'), ('outro', 'Outro')], default='solteiro', max_length=30),
        ),
        migrations.AddField(
            model_name='buyer',
            name='function',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='buyer',
            name='nascimento',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='buyer',
            name='pis',
            field=models.CharField(default='', max_length=14, unique=True),
        ),
        migrations.AddField(
            model_name='buyer',
            name='rg',
            field=models.CharField(default='', max_length=30, unique=True),
        ),
        migrations.AddField(
            model_name='buyer',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='name',
            field=models.CharField(max_length=120),
        ),
    ]
