# Generated by Django 5.2.10 on 2026-01-26 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20260126_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='setor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='store.season', verbose_name='Setor'),
        ),
    ]
