# Generated by Django 5.2.10 on 2026-01-27 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_product_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
    ]
