# Generated by Django 5.2.10 on 2026-01-27 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_order_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.season'),
        ),
    ]
